### ISSUE TITLE
Hide options from chosen user groups

### ISSUE THREAD

**Issue by mrtopher** [mrtopher/dashEE#15]
Add ability for super administrators to hide options like the Widgets and Settings buttons from certain membership groups essentially locking down their dashboard layout so it cannot be changed.

Requested via devot-ee: http://devot-ee.com/add-ons/support/dashee/viewthread/3738/

**Comment by marc524** [comment]
Just came in here to post the same suggestion. I created a Carthrob widget to display the latest orders, then realized there are going to be junior admins who have access to the cp who shouldn't be seeing that information.

If Dashee could be configured the way Zenbu or Zoo Flex Admin is where a Super Admin sets what widgets are dispalyed based on Member Groups, that would be fantastic.

Still a very cool addon. Thanks Chris!

**Comment by mrtopher** [comment]
Hey marc524, thanks for the info!

There is a way to require certain permissions for specific widgets by adding the ["permissions" method](http://www.christophermonnat.com/code/dashee/creating-widgets/#permissions) to your widget file. Once added you can place whatever checks you want into that file and if the user doesn't meet those parameters then the widget will not be listed for them to add to their dashboard. If you add these parameters after a user has installed the widget and they don't meet the requirements then the widget will simply be removed from their dashboard.

So in your example I would probably be checking to see if the user has permission to access the Carthrob module or perhaps a permission within that module. Does that sound like it would solve your problem or are you looking for more of a point a click solution?

**Comment by mrtopher** [comment]
Added with version 1.5.

**Comment by marc524** [comment]
Hey Chris,
finally got around to testing this out and it works really well. One thing
I discovered is in the Settings screen, I had to click Reset for a member
group first before applying the new custom saved layout. Otherwise it was
sticking with the default. No biggie. It may have been a legacy thing from
the previous version. Not sure.

Also, I attached an my version of the Recent Entries widget that includes a
third table column to show what channel that entry belongs to. It's more
useful for me at least. Let me know your thoughts on it. I can put it on
git if you want to make it an optional widget, but feel free to use it in
core if you want.

-Marc

On Mon, Jan 30, 2012 at 7:14 PM, Chris Monnat <
reply@reply.github.com

**Comment by mrtopher** [comment]
Hey Marc,

I'll look into that reset thing. If the user has already customized their dashboard and then you assign their group a layout then it will not apply to that user... assigned layouts only apply to users accessing the dashboard for the first time. So it sounds to me like everything worked the way it was supposed to. But I'll take it for a spin just in case.

I didn't get your attachment. Go ahead and send it to chris@monnat.org and I'll take a look.

Thanks, CM
