### ISSUE TITLE
Opening Widgets panel causes site to load in its stead

### ISSUE THREAD

**Issue by furioursus** [mrtopher/dashEE#2]
Running 2.2.2, and quite a few add ons, but none that should affect the homepage. When I click "widgets", I see the site load in the window, but since it is being called to from the system folder, anything that isn't a hardcoded path doesn't render.

**Comment by mrtopher** [comment]
Ok, I think I got this figured out. I was including index.php in the AJAX calls of the dashee.js file in the themes folder. Since you were not accessing your control panel that way (you are using admin.php) that was causing the problem. I reproduced it myself and think I have corrected the problem.

Please download the latest and try again. You should only need to replace the /themes/third_party/dahsee/js/dashee.js file and do a hard refresh.

Give it a shot and let me know how you make out.

CM
